language: node_js

node_js:
  # See: https://github.com/facebook/jest/issues/8069#issuecomment-470307590
  - '11.10.1'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn run test
  - codecov
